### PR TITLE
USI integration patch updates

### PR DESCRIPTION
**Pull request by Wyzard256**
This is a collection of changes to `NFElectricalUSI.cfg` to resolve a few remaining integration issues with USI mods:

* The reactor in the MKS "Duna" PDU wasn't modified to use the NFE reactor modules.  There was a patch for its predecessor, the legacy MKS PDU, which no longer exists; I've updated it for the Duna PDU instead.
* I also added a patch for the larger MKS "Tundra" PDU, derived from the Duna patch and the ratios between the two parts' unpatched stats.
* Compared to the NFE reactors and the other patched USI reactors, the Duna and Tundra PDUs were very inexpensive for the amount of power they produced.  I brought their costs into line with the other reactors.
* The MKS reactors still had the USI mechanism for transferring EnrichedUranium and DepletedFuel: a "perform maintenance" command that could be performed by an engineer on EVA.  That's redundant with the NFE transfer commands (and could be performed by a 0-star engineer, unlike the NFE version), so I removed it.
* The USI nuclear fuel and waste Kontainers lacked NFE's RadioactiveStorageContainer module, so they couldn't have their contents transferred using NFE.  I added the module.
* The Whirlijig's ability to extract EnrichedUranium from Ore should be disabled when MKS is installed (since MKS has a different system for that), but it was actually disabled when *any* USI mod was installed, such as USI-LS or Konstruction.  I changed it to check specifically for MKS.

The USI fuel/waste containers still have `USI_ModuleResourceWarehouse`, which automatically transfers resources between nearby bases on-demand.  I haven't tested whether that actually works for EnrichedUranium and DepletedFuel (both of which have `flowMode = NO_FLOW` and `transfer = NONE`), but if it does, it's not clear whether it should NFE should disable it.  On one hand, it allows dangerous radioactive materials to be transferred without an engineer; on the other hand, MKS bases are often built as groups of small separate craft located near each other (to avoid kraken physics), and having to manually move uranium between them may be tedious.

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
If you could target this to dev, that'd be great.

**Comment by Wyzard256** [comment]
Retargeted to dev as requested.

**Comment by Wyzard256** [comment]
As mentioned above, btw, it may be a good idea to remove the USI "resource warehouse" functionality from the USI fuel/waste containers, since it allows fuel transfers without an engineer.  If you think it should stay, though, it probably ought to be added to the NFE fuel/waste containers too.  I'm willing to make either change — let me know.

**Comment by ChrisAdderley** [comment]
I think it makes sense to keep the warehouse stuff for USI. That's largely a convenience feature and a big sell of the mod. Let's also add it to the NFE containers,

**Comment by Wyzard256** [comment]
OK, I added `USI_ModuleResourceWarehouse` to the NFE fuel/waste containers.  I also added `USI_ModuleRecycleBin` since the USI containers have it, though nothing seems to actually utilize it right now.

I *think* this takes care of all the remaining integration issues between USI and NFE nuclear parts.  I've done my best to match the established NFE parts' balancing, but some balance tweaks may be needed by someone with more experience in such things than me.

(I notice that some of the USI Karibou container parts have storage for EnrichedUranium+DepletedUranium, but that looks like a bug, so I don't plan to add RadioactiveStorageContainer patches for those parts.)

**Comment by ChrisAdderley** [comment]
Merged, thanks!

**Pull request merged**
