### PR TITLE
Added PatchManger Integration

### PR DESCRIPTION
**Pull request by DanStaal**
Made the RTG and USI-reactor patches work with PatchManager - players will be able to activate/deactivate the patches using an in-game UI if they have PatchManager installed.

Behavior of the patches has not changed, and without PatchManager there should be no effect.  (Except for it being a bit harder to find the decaying RTG’s patch - note that it is not active by default.)

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
So... it looks like this moves things into the GameData directory by default. Won't this then cause the patch to be active all the time in the case where a user does not have PatchManager installed?

**Comment by DanStaal** [comment]
No - because MM skips PluginData folders, and the RTG patch is inside a PluginData folder.  (The USI patch isn't - and is therefore active without PatchManager.)

**Comment by blackliner** [comment]
Not if its in a pluginData folder.

**Comment by blackliner** [comment]
Is anyone telling the CKAN guys (linuxguru etc) about these changes, because atm these patches are handled as seperate modpackages?

**Comment by ChrisAdderley** [comment]
I am reluctant to merge this exactly because of that, and because it makes the installation instructions in a non PatchManager context complex.

**Comment by DanStaal** [comment]
Well, linuxguru is also the author of PatchManager, so if it gets integrated then mentioning in that thread that support has been added is likely a way to cover both there.

Is the USI patch also handled as a separate modpack?  That's really where I started - and it doesn't change the defaults there either.  If you wanted to leave the RTG patch as an extra I can probably reset to that fairly quickly - I just thought that PatchManager is definitely a better way to handle 'Extras' packs in the long run, even if there is a bit of friction in the short run.

**Comment by blackliner** [comment]
Actually, I do really like the CKAN way, because as long as patch manager can't spare me the game restart, where is the players profit? Another tool to handle...

**Comment by ChrisAdderley** [comment]
Mostly my opinion is screw CKAN, so that's not really a point one way or another... but basically it replaces CKAN+NFE with CKAN+PatchManager+NFE for the same functionality, and makes it harder for people not using PM to use them.

It's a good idea in concept but it may be out of scope for this update cycle. I would like to put it to more people on the forums to see what the opinion is on this. If this happened I would want to convert the full set of extras patches from the other mods as well and completely deprecate the old way of doing things.

**Comment by DanStaal** [comment]
In theory PatchManager can spare you a game restart - all you have to do is do a MM refresh.  Which in my experience is essentially the same as a restart, but....

CKAN didn't work at all for me when I started with KSP, and I'm not sure if it works on my new box.  I work on manual installs, so I like not having to fiddle with the extra folder, personally.

I take your point on scope on this update cycle however.  Would you like me to expand this PR to cover all the patches?  I focused on these two as the ones most often changed, in my opinion, but I could do the rest and then you'd have the PR ready whenever, if you wanted it.

**Comment by linuxgurugamer** [comment]
Sorry, PatchManager, can't spare  you a game restart.  Doing a MM refresh doesn't always work properly.

Due to the way that KSP deals with files, and MM deals with patches, I'm afraid that with ANY change of patches, however you do it, you get the best results by restarting the game

**Comment by DanStaal** [comment]
@linuxgurugamer , can you comment on the CKAN issue?

**Comment by linuxgurugamer** [comment]
First, keep in mind that regarding CKAN, I'm not an expert, I just have scripts to generate new .netkan files and the abililty to do merges and edits in the main repo.

That being said, doing it via CKAN does remove a step, but, CKAN isn't perfect, despite my support for it.

The nice thing about PatchManager (IMHO), is that you can add/remove one or more patches from one or more mods at the same time, without any external calls.  No possibility of CKAN getting confused, etc.

But, this is Chris's call.  I'd be happy to discuss this with whoever is maintaining the CKAN modpacks for this.

**Comment by ChrisAdderley** [comment]
I think I've decided not to take this approach.

**Pull request closed without merging**
