### PR TITLE
Draft russian translation 0.3

### PR DESCRIPTION
**Pull request by doktorjet**
1. Real world capacitors ("конденсаторы") physicaly cannot behave like those fictional "Capacitors". 
Ionistors ("supercapacitors" in USA english IIRC) seem to be the closest real world analogue, having limitless cycles and allowing "slow" discharge, but they are much less mass-efficient than generic batteries (opposite to game "Capacitors")...
Maybe I should use a neutral word "накопитель" which is not linked to any exact energy storage method? (english word is "accumulator", don't confuse with russian "аккумулятор" which literally means "rechargeable battery")  
Final decision depends on what exact near-future technology do you have in mind for that "capacitors"? 

2. Do you mean something in particular with those manufacturer names? Or are they just "something random sounding proper"? Close-to literal russian counterparts sound weird.

3. #LOC_NFElectrical_battery-25_description uses "Batt Man Batteries" instead of "Batt-Direct Batteries" - is it a typo or what? 

4. I know, the proper russian word for refinement is "аффинаж" (fr->en "affination"), but there are tons of kids playing KSP - they won't understand it. So it's just a mundane term "очистка".

5. #LOC_NFElectrical_rtg-0625_description - Are you sure it must be "Blutonium" instead of plutonium? Uranium is written properly in other descriptions.

6. #LOC_NFElectrical_nuclearfuel-0625_title and others - there is no good russian word for drum-shaped container. Literal translation would be either "барабан" (percussion instrument or brake drum) or "стальная бочка" ("steel barrel").

7. #LOC_NFElectrical_reactor-0625_description - Considering description, MX-0 is not a proper reactor. So, what is it? ASRG (radioisotope stirling generator)? Description should be a bit different for ASRG.

8. But PB-AS-NUK part does look much more like ASRG prototype. Shouldn't #LOC_NFElectrical_rtg-0625_description have a description with Stirling engine instead? 

9. #LOC_NFElectrical_reactor-375_title - all adjectives are too long. Translated as "Б.Л.И.Н." - literally "pancake". =^_^=

10. Ingame testing shown that units of measurement are not translated. kW, SC/s and EC/s are still english both in part info and in control panels. Though I'm already a bit worried about SC abbreviation... russian one looks like "ХЗ" (Хранимый Заряд) which is kinda weird, as it may be misinterpreted for obscene abbreviation of "хуй знает" (literally "dick knows"). 
Oh! I have an idea. "НЗ" (Накопленный Заряд) - it still can be misinterpreted for "emergency rations", but rations are not obscene. =^_^=

11. In part info (capacitors) there is shown "/s" instead of expected "SC/s" while charging. In control panel it's shown correct.

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
Honestly dude, you translate as you want to. I don't speak Russian, so have no personal stake in how things are translated. If you decide you think something makes sense some way, go for it.

**Comment by doktorjet** [comment]
P.10 and P.11 are actually bugs. Those will affect all translations - not just russian.

**Comment by ChrisAdderley** [comment]
https://github.com/ChrisAdderley/NearFutureElectrical/issues/81 will be slated for 0.9,.5

**Comment by ChrisAdderley** [comment]
If you compare against the dev branch, you can see the couple changes I made to support units in all cases. There are 4 or 5 new lines to translate as a result.

**Comment by doktorjet** [comment]
That's nice. Updated translation to 0.3

**Pull request merged**
