### PR TITLE
Make FissionGenerator adaptable for KSPI-E

### PR DESCRIPTION
**Pull request by arivaldh**
delta computation is meaningless. Stock mechanics will not add more resource than the fuel tanks can hold, and will return the value added/removed.
Added field: AddedToFuelTanks that will allow KSPI-E to properly convert EC to MJ.
KSPI-E needs to requestResource for EC that was added, in order to convert the whole to MJ and start power distribution from there.
Change in KSPI-E:
https://github.com/arivaldh/KSP-Interstellar-Extended/commit/7ae65f57d5f964efa17ac1a0aa5efcf0f89f79b5

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
I'm not likely to add this - KSPI should really be using its own reactor implementation to avoid player confusion.

**Comment by arivaldh** [comment]
I'm a bit confused,

From a technical perspective:
- this change doesn't change any behavior of Near Future Fission Generator.
- this change only exposes to read how much EC was added to fuel tanks due to EC generation.

From a Near Future Technologies mods perspective:
- no change to standalone version of the plugins.

From community perspective:
- there are many requests for NFE & NFP to work along side KSPI-E.

I personally don't understand your attitude.

**Comment by ChrisAdderley** [comment]
Community perspective:
* NFP and NFE will not work well alongside KSPI-E because of radically different balance paradigms. As far as I was aware from a year or so ago, the author of KSPI-E agreed with me here.

KSPI-E perspective:
* It occurs to me that this is actually not correct and this PR might be pointless. If you want to weirdly hybridize the two mods, you can already sample the `CurrentGeneration` property. The reactor module works to constantly generate power in terms of its output - the output scaling is only there to mitigate an internal KSP resource allocation bug that occurs at higher timewarps. If you want to get the amount of power generated by the reactor it should always be `CurrentGeneration`

**Comment by arivaldh** [comment]
CurrentGeneration property doesn't say about about the amount of power generated by the reactor.
It say how much the reactor CAN generate. Not how much EC did it generated.

What output scaling? I haven't changed/introduced anything like it. I have added a KSP field that will externalize how much EC was actually added because of power generation of this module. Nothing else. Are you sure you're looking at my changes?

And FreeThinker ASKED me to implement adapter for NearFutureElectrical Fission Reactor.

**Comment by arivaldh** [comment]
Let me comment on the old code:
-                  double generated = (double)(Mathf.Clamp01(CurrentHeatUsed / HeatUsed) * PowerGeneration);
-                  double delta = 0d;
-                  for (int i = 0; i < this.vessel.parts.Count; i++)
-                  {
-                      if (this.vessel.parts[i].Resources.Get(PartResourceLibrary.Instance.GetDefinition("ElectricCharge").id) != null)
-                           delta += this.vessel.parts[i].Resources.Get(PartResourceLibrary.Instance.GetDefinition("ElectricCharge").id).maxAmount -
-                                this.vessel.parts[i].Resources.Get(PartResourceLibrary.Instance.GetDefinition("ElectricCharge").id).amount;
-                  }

generated - the amount of EC that can be generated during a single second.
Delta - the amount of free storage for EC.

-                  double generatedActual = Math.Min(delta, TimeWarp.fixedDeltaTime * generated);
-
-                  double amt = this.part.RequestResource("ElectricCharge",  -generatedActual);
-
-                  if (double.IsNaN(generated))
-                      generated = 0.0;
-
-                  CurrentGeneration = (float)generated;

generatedActual - not more than the amount of free space, and up to the amount of possible generated power in the time tick defined by fixedDeltaTime, or the other way around.
amt - the amount that was actually ADDED to the tanks (it will be negative).
CurrentGeneration = generated.
this.part.RequestResource won't add more resources than the space available in fuel tanks. And amt is discarded - not used at all.

> If you considered the amount added by the reactor, you would have an incorrect relationship between fuel consumed and electricity generated (ie, less would be generated than should be given the fuel consumption).

I do not want to modify fuel consumption etc.  I don't understand why you think so. I want to know how much EC was added since KSPI-E needs MJ. So KSPI-E implementation requests EC that was (actually) generated/added, and outputs all power in MJ.

> If you or freethinker want to change this behaviour, you should be patching out the NFE reactor modules and adding KSPIEs.

I do not want to change ANY NearFutureElectric behavior.

If you truly believe that delta computation is necessary, I can restore it, but I checked the change, and I haven't found any change in behavior of NFE fission generator. Please let me know which scenario will be affected by this change.

**Comment by ChrisAdderley** [comment]
You've come out very combative with this MR from the start. Take it easy.

> I do not want to modify fuel consumption etc. I don't understand why you think so. I want to know how much EC was added since KSPI-E needs MJ. So KSPI-E implementation requests EC that was (actually) generated/added, and outputs all power in MJ.

I feel like you don't understand what happens procedurally here. Here are my assumptions:
* Power is generated by the reactor in EC
* You want to convert the amount of power generated by the reactor to MJ
That is simple enough, right? To do this you only need to know the amount of power generated by the reactor. You need know nothing about storage or anything like that! This is because the behaviour of an NFE reactor is specific in that it **generates the same amount of power regardless of the amount of storage available**.
You may be confused because this is different than some systems in KSP, that throttle themselves based on the amount of power storage available. This is not the case here. This is a design decision.

To convert the EC generated to MJ you should:
* Check the amount of power being currently generated
* Convert that to MJ
* Add the MJ to the vehicle through whatever logic KSPI uses to handle MJ storage.

What you seem to think you need to do is this:
* Check the amount of power that has been added to the vehicle via the addition of power
* Convert that to MJ
* Add the MJ to the vehicle through whatever logic KSPI uses to handle MJ storage.
This method will result in incorrect values, because the NFE reactor will consume fuel resources as if it was running at full load even if no EC is being added. Even if no EC is being added, you should still be adding an appropriate amount of MJ and letting the MJ storage handle the fill-up. 

Does this make sense?

**Comment by arivaldh** [comment]
I do understand what is going on in here. You just don't listen. Again.

> To convert the EC generated to MJ you should:
> 
>     Check the amount of power being currently generated
>     Convert that to MJ
>     Add the MJ to the vehicle through whatever logic KSPI uses to handle MJ storage.
>
> What you seem to think you need to do is this:
> 
>     Check the amount of power that has been added to the vehicle via the addition of power
>     Convert that to MJ
>     Add the MJ to the vehicle through whatever logic KSPI uses to handle MJ storage.
>     This method will result in incorrect values, because the NFE reactor will consume fuel resources as if it was running at full load even if no EC is being added. Even if no EC is being added, you should still be adding an appropriate amount of MJ and letting the MJ storage handle the fill-up.

NO! What I need to do is:
- Subtract ADDED EC. So that ALL of the power will be generated through MJ mechanism. (that's why I need how much was added).
- Convert to MJ WHOLE GENERATED POWER / 1000.

**Without the first step Generator will generate TWICE the amount. Once in EC, second in MJ.**

From PR comment:
> KSPI-E needs to requestResource for EC that was **added**, in order to convert the **whole** to MJ and start power distribution from there.
**whole - not added.**

From previous comment:
>  I want to know how much EC was added since KSPI-E needs MJ. So KSPI-E implementation requests EC that was **(actually) generated/added, and outputs all power in MJ.**
Request EC actually generated/added and output ALL POWER generated in MJ.

Both means that generator will output constantly the SAME amount of MJ, regardless of how much EC was actually added to tanks.

**It's also clearly visible in the Commit from KSPI-E that WAS added to PR comment.**

Please, bear in mind that telling someone what he thinks isn't a good strategy. Even more so if you're saying incorrect things since I already explained at least two times what's is the flow I want to have.

**Comment by ChrisAdderley** [comment]
Oh I forgot to get back to this. 
This goes against the support plan for my mods. I will not be merging this.

**Comment by arivaldh** [comment]
Sadly there's only one logic - but there can be many beliefs and behaviors that are present regardless of logic.

You don't want to have any KSPI-E integration. I understood it, even though I don't agree with it.
Your only argument is "because", and you have shown that you have neither read nor executed provided change in NFE or in KSPI-E (since you have constantly argued about the flow contrary to the provided code).

You haven't answered any questions about which functionality is impacted by the change, or in which scenario. In my opinion there's no change in functionality of standalone NFE, it will be faster, and it will allow integration with KSPI-E (and possibly other mods).

In the end you can do whatever you want to.

**Pull request closed without merging**
